title: "<p align='center'>Souhardya Biswas</p>"
logo: "/assets/img/logo.png"

description: |
  <p align='center'>
    <a href="pdf/resume.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
    <a href="https://github.com/sajankedia">GitHub</a>
  </p>
  <br>
  <p align='center'>
    I'm a professional working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
    Currently, I'm handling real-time Ad call data in the AdTech domain.
    I have valuable experience, having worked with IBM Research at the Big Data Analytics team for a period.
    With 3 years in the AdTech domain, I bring expertise in various aspects of the field.
  </p>

theme: jekyll-theme-minimal
